server:
  port: "8080"

database:
#  host: 127.0.0.1
#  host: docker.for.mac.localhost
  host: host.docker.internal
  port: 5432
  name: todoapp
  username: root
  password: secret
  options:
    sslmode:
      - disable
  max_idle_connection: 2
  max_open_connection: 2
  max_connection_lifetime: 300
  batch_size: 10
  slow_threshold: 10

redis:
#  host: 127.0.0.1
#  host: docker.for.mac.localhost
  host: host.docker.internal
  port: 6379
  password: ""
  db: 0

rabbitmq:
#  host: docker.for.mac.localhost
  host: host.docker.internal
  port: 5672
  user: guest
  password: guest
  queue_name: todo_queue
  exchange_name: todo_exchange
  exchange_type: topic
  routing_key: "#.notification"
  prefetch_count: 1
  worker_pool_count: 2